

services:
  automation-test-report:
    container_name: automation-test-report
    # build: .
    image: ghcr.io/lensimax/unrealengine-automationtestreportserver-docker:UE-5.3
    restart: always
    volumes:
        - ./.containerdata:/report-site/site
    ports:
        - "8080:8080"
